### PR TITLE
New setting for Google Tag Manager ID

### PR DESCRIPTION
**Pull request by rperello**

### CODE REVIEW

**Comment by sdebacker** [comment]
Thank you, shouldn't we add the tag manager installation code in /core/resources/views/public/master.blade.php ?

**Comment by rperello** [comment]
Yes, didn't sent you a pull request on TypiCMS/Core ?

**Comment by sdebacker** [comment]
I see no PR to Core coming from you.

**Comment by sdebacker** [comment]
It should be good to put tag manager and analytics integration code in partials like _google_tag_manager.blade.php for example.

**Comment by rperello** [comment]
Ok, i Will put It in a partial and send you a pull request ;)

**Pull request merged**
